version: '3.8'

services:
  # Zookeeper Ensemble for SolrCloud coordination
  zookeeper1:
    image: zookeeper:3.8
    hostname: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    volumes:
      - zk1-data:/data
      - zk1-datalog:/datalog
    networks:
      - solr-network

  zookeeper2:
    image: zookeeper:3.8
    hostname: zookeeper2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    volumes:
      - zk2-data:/data
      - zk2-datalog:/datalog
    networks:
      - solr-network

  zookeeper3:
    image: zookeeper:3.8
    hostname: zookeeper3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    volumes:
      - zk3-data:/data
      - zk3-datalog:/datalog
    networks:
      - solr-network

  # SolrCloud Nodes
  solr1:
    image: solr:9.4
    hostname: solr1
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - SOLR_HOST=solr1
      - SOLR_PORT=8983
      - SOLR_HEAP=1g
    volumes:
      - solr1-data:/var/solr
      - ./solr-init:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - solr-network
    command: >
      bash -c "
        solr-precreate ecommerce_products /docker-entrypoint-initdb.d/configsets/ecommerce -z zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      "

  solr2:
    image: solr:9.4
    hostname: solr2
    ports:
      - "8984:8983"
    environment:
      - ZK_HOST=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - SOLR_HOST=solr2
      - SOLR_PORT=8983
      - SOLR_HEAP=1g
    volumes:
      - solr2-data:/var/solr
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - solr1
    networks:
      - solr-network
    command: >
      bash -c "
        solr start -cloud -z zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 -h solr2 -p 8983 -f
      "

  solr3:
    image: solr:9.4
    hostname: solr3
    ports:
      - "8985:8983"
    environment:
      - ZK_HOST=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - SOLR_HOST=solr3
      - SOLR_PORT=8983
      - SOLR_HEAP=1g
    volumes:
      - solr3-data:/var/solr
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - solr1
    networks:
      - solr-network
    command: >
      bash -c "
        solr start -cloud -z zookeeper1:2181,zookeeper2:2181,zookeeper3:2181 -h solr3 -p 8983 -f
      "

networks:
  solr-network:
    driver: bridge

volumes:
  zk1-data:
  zk1-datalog:
  zk2-data:
  zk2-datalog:
  zk3-data:
  zk3-datalog:
  solr1-data:
  solr2-data:
  solr3-data:
