name: Solr Optimizer CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
          pip install -e .[dev]
      - name: Check formatting with black
        run: black --check .
      - name: Check import sorting with isort
        run: isort --check-only --profile black .
      - name: Lint with flake8
        run: flake8 .
      - name: Type check with mypy
        run: mypy solr_optimizer

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -e .[dev,test]
      - name: Test with pytest
        run: pytest --cov=solr_optimizer tests/

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel
      - name: Build package
        run: python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          
  integration:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name != 'pull_request'
    services:
      solr:
        image: solr:9.3.0
        ports:
          - 8983:8983
        options: >-
          --health-cmd "wget -q -O - http://localhost:8983/solr/admin/ping?wt=json | grep status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run integration tests
        run: pytest tests/integration/
        env:
          SOLR_URL: http://localhost:8983/solr

  docs:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
      - name: Build documentation
        run: |
          cd docs
          make html
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build/html/
